Bump down to 1.4.65 because of scikit-learn error
```
    docassemble-webapp 1.4.88 depends on scikit-learn==1.3.0
    docassemble-alweaver 1.10.3 depends on scikit-learn>=0.0
    formfyxer 0.3.0a1 depends on scikit-learn==1.2.2
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Error: Process completed with exit code 1.
```