Ran and corrected mypy issues on ALWeaver
Had to ignore most of the imported libraries. Had a few issues that I couldn't
solve and had to inline ignore:

* docassemble/ALWeaver/field_grouping.py:33: error: "Iterable[Object]" has no attribute "__next__"
  Not sure where it's getting that type from pikepdf, but it's likely wrong
  there. That code does work.
* docassemble/ALWeaver/validate_docx_files.py:40: error: "TemplateSyntaxError"
  has no attribute "docx_context": they type doesn't, but docxtpl does manually
  add that attribute:
  https://github.com/elapouya/python-docx-template/blob/9b4e623c3c1ebb1a1af67a15579010c6d1933d74/docxtpl/template.py#L241
  So we need to probably change upstream to return a different type? Unclear